#!/bin/bash

usage()
{
    echo "get a list of dependencies (based on libraries) for a deb control file from"
    echo "a bunch of files/dirs recursively"
    echo
    echo "usage: $(basename $0) FILE1 [FILE2] ..."
}


if [ ! $# -ge 1 ]; then
    usage
    exit 1
fi


libs=$((find . -type f | xargs ldd 2>/dev/null) | grep -v "not found" | awk '/=>/ {print $3}' | sort | uniq)
echo
echo libs: $libs

pkgs=$(dpkg -S $libs | awk -F: '{print $1}' | sort | uniq)
echo
echo pkgs: $pkgs

echo
echo "comma-delimited for DEBIAN/control Depends:"
echo $pkgs | sed 's| |, |g'
