#!/bin/bash
#
# RuckusRD - a super awesome, yet simple, mkinitrd replacement
#
# Copyright 2012-2018 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script is a utility for creating a self extracting executable that runs
# an install script after extracting to a temp directory.
#
# FIXME: fix lame command line parsing and add usage
#
filename=$1
script=$2
shift 2
payload=$*
echo filename: $filename
echo script: $script
echo payload: $payload

# create the initial installer script
cat > $filename <<EOF
#!/bin/sh
skip=__SKIP__

basedir=\`mktemp -dt \\\`basename \$0\\\`-XXXX\`

echo -n "extracting archive to \$basedir... "
tail -n +\$skip \$0 | zcat | tar -x --no-same-owner --no-same-permissions -C \$basedir && echo DONE || { echo FAIL; exit 1; }

cd \$basedir
`cat $script`

exit 0
EOF

# sed the actual length into it
skip=$((`wc -l $filename | awk '{print $1}'`+1))
echo skip: $skip
sed -i "s|__SKIP__|$skip|" $filename

# and now append the payload
echo -n "appending payload... "
(tar -c $payload | gzip >> $filename) || { echo FAIL; exit 1; }
echo DONE

# and make it executable
echo -n "making $filename executable... "
chmod +x $filename && echo DONE || { echo FAIL; exit 1; }

exit 0
