#!/bin/bash
#
# RuckusRD - a super awesome, yet simple, mkinitrd replacement
#
# Copyright 2012-2019 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script is a utility for installing a built kernel onto a remote machine
# via ssh/rsync.  First run `kernel_builder`, then run this.

export SRP_ROOT=$PWD/FOO

VERSION=$(basename $SRP_ROOT/lib/modules/*)
target_host=$1

if [ -z "$target_host" ]; then
    echo "need to specify target host"
    exit -1
fi

echo VERSION: $VERSION
echo target_host: $target_host

# we do this in a single line to reduce the number of ssh authentications
# necessary
echo removing preexisting modules and headers on $target_host
ssh root@$target_host rm -rf /lib/modules/$VERSION /usr/src/linux-headers-$VERSION || exit 1

echo installing files on $target_host
rsync -vzurltD --keep-dirlinks $SRP_ROOT/ root@$target_host:/ || exit 2
