#!/bin/bash
#
# RuckusRD - a super awesome, yet simple, mkinitrd replacement
#
# Copyright 2012-2020 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script is a utility for creating a self-extracting installer for a built
# Linux kernel.  First run `kernel_builder`, then run this.
#
export SRP_ROOT=$PWD/FOO

VERSION=$(basename $SRP_ROOT/lib/modules/*)

filename=$PWD/kernel-installer-$VERSION.sh

# setup a tmpdir
tmpdir=`mktemp -dt \`basename $0\`-XXXX`

# create the installer script
#
# FIXME: should check for VERSION symlink, remove what it points to if
#        detected.
#
# FIXME: why do we tar FOO to stdout, pipe that into tar to install?  was it
#        just to avoid having to retest something else when i split
#        extracenator into a seperate script?  We could do 'cp -a' or something
#        similar instead... right?
#
cat > $tmpdir/installer <<EOF
echo -n "removing preexisting modules in /lib/modules/$VERSION... "
rm -rf /lib/modules/$VERSION && echo DONE || { echo FAIL; exit 1; }

echo -n "removing preexisting headers in /usr/src/linux-headers-$VERSION... "
rm -rf /usr/src/linux-headers-$VERSION && echo DONE || { echo FAIL; exit 1; }

echo -n "extracting archive... "
(tar -C FOO -c . | tar -x --no-same-owner --no-same-permissions -C /) && echo DONE || { echo FAIL; exit 1; }

echo
echo "!! don't forget to update your bootloader (e.g., grub, extlinux) !!"
echo

EOF

# NOTE: $* is so we can pass additional arguments to extractenator (e.g.,
#       --comp).
#
extractenator -f $filename -s $tmpdir/installer FOO $* || exit 1

rm -rf $tmpdir
exit 0
