#!/bin/ash
#
# Copyright 2012-2025 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script mounts the required virtual filesystems on /sysroot (and mounts
# /sysroot if not already mounted).

. /ruckusrd-common.sh

# exit immediately if a command fails
set -e

if ! (grep -q /sysroot /proc/mounts); then
    mount_sysroot $*
fi

mount proc -t proc /sysroot/proc
mount sys -t sysfs /sysroot/sys
mount --rbind /dev /sysroot/dev
mount --make-rslave /sysroot/dev

echo "You can now chroot into /sysroot with the following command:"
echo
echo "  chroot /sysroot /usr/bin/env -i HOME=/root TERM=\$TERM /bin/bash --login"
echo
