#!/bin/bash
#
# RuckusRD - a super awesome, yet simple, mkinitrd replacement
#
# Copyright 2012-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script is a derivative of fedora's livecd-creator's mayflower script,
# written by David Zeuthen <davidz@redhat.com>.
#
# It's been largely rewritten (multiple times now) to be a mkinitrd replacement
# that can be used on embedded systems, flash drives, live CDs, and normal
# desktop Linux systems.  See the file README for details.


shopt -s nullglob


# assume we're in the source tree if $PWD/linuxrc exists
if [ -f $(dirname $0)/linuxrc ]; then
    LIBDIR=$(realpath $(dirname $0))
else
    LIBDIR=__LIBDIR__
fi
. $LIBDIR/ruckusrd.conf


decho()
{
    if [ "$opt_verbose" != "0" ]; then
        echo "$*"
    fi
}


usage()
{
    echo "RuckusRD v$VERSION - a super awesome, yet simple, mkinitrd replacement"
    echo "Copyright (C) 2012-2021 Michael D Labriola <michael.d.labriola@gmail.com>"
    echo
    echo "usage: $(basename $0) [--help] [--verbose] [--version] [-f] [-b basedir] [-c best|fast] <out-initrd-image> <kernel-version>"
    echo
    echo "example: $(basename $0) /boot/myinitramfs.img \`uname -r\`"
}


cleanup()
{
    retcode=$1
    rm -rf $TEMPDIR
    exit $retcode
}


opt_allow_overwrite=0
opt_verbose=0
INITRAMFS_TARGET=""
KERNEL=""
BASEDIR="/"
COMPMODE="fast"
while [ $# -gt 0 ] ; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
	-V|--version)
	    echo v$VERSION
	    exit 0
	    ;;
        -f)
            opt_allow_overwrite=1
            ;;
        -v|--verbose)
            opt_verbose=1
            ;;
        -b)
            BASEDIR=$2
            shift
            ;;
        -c)
            COMPMODE=$2
            shift
            ;;
        *)
            if [ -z "$INITRAMFS_TARGET" ] ; then
                INITRAMFS_TARGET=$1
            elif [ -z "$KERNEL" ] ; then
                KERNEL=$1
            else
                echo "Unknown option or parameter \"$1\""
                echo
                usage
                exit 1
            fi
            ;;
        *)
            ;;
    esac

    shift
done

if [ -z "$INITRAMFS_TARGET" -o -z "$KERNEL" ] ; then
    usage
    exit 1
fi

if [  "$opt_allow_overwrite" == "0" ] ; then
    if [ -e $INITRAMFS_TARGET ] ; then
	echo "Image $INITRAMFS_TARGET already exists. Use -f to overwrite"
	exit 1
    fi
fi

echo "Building an initramfs at $INITRAMFS_TARGET for kernel $KERNEL"


original_pwd=$PWD

cp="cp -a"
cpio="cpio"
mkdir="mkdir -p"
mv="mv"
xz="xz"
ln="ln"
if [ "$opt_verbose" != "0" ]; then
    cp+=" -v"
    mkdir+=" -v"
    mv+=" -v"
    xz+=" -v"
    ln+=" -v"
else
    cpio+=" --quiet"
fi

decho '********** PREPPING TEMPDIR ****************************************************'
# setup our working tempdir
TEMPDIR=`mktemp -dt ruckusrd-XXXX` &&
$mkdir $TEMPDIR/initramfs || cleanup 1

# populate initramfs w/ pregenerted archive
pushd >/dev/null $TEMPDIR/initramfs &&
$xz -dc $LIBDIR/initramfs.cpio.xz | $cpio --extract &&
popd >/dev/null || cleanup 1


decho '********** PREPPING INITRAMFS MODULE DIR ***************************************'
HOSTMODDIR=$(realpath -s $BASEDIR/lib/modules/$KERNEL)
decho HOSTMODDIR=$HOSTMODDIR
if [ -h $HOSTMODDIR ]; then
    HOSTMODDIR=$(realpath $HOSTMODDIR)
    decho HOSTMODDIR is a symlink pointing to $HOSTMODDIR
    DESTMODDIR=$TEMPDIR/initramfs/lib/modules/$(basename $HOSTMODDIR)
    decho DESTMODDIR=$DESTMODDIR
    $mkdir $(dirname $DESTMODDIR) || cleanup 1
    $ln -s $(basename $HOSTMODDIR) $TEMPDIR/initramfs/lib/modules/$KERNEL || cleanup 1
else
    DESTMODDIR=$TEMPDIR/initramfs/lib/modules/$KERNEL
    decho DESTMODDIR=$DESTMODDIR
    $mkdir $(dirname $DESTMODDIR) || cleanup 1
fi


decho '********** INSTALLING MODULES **************************************************'
# Copy entire modules dir over
#
# NOTE: Now that we're copying the entire tree as-is, we no longer have to
#       search for missing dependencies or rerun depmod.
#
# FIXME: maybe this shouldn't be the default behavior?  allow command line flag
#        to do subset of modules? --only-needed-modules?
#
$cp -a $(realpath $HOSTMODDIR) $DESTMODDIR || cleanup 1


decho '********** PREPPING INITRAMFS HEADER DIR ***************************************'
HOSTHDRDIR=$(realpath -s $BASEDIR/usr/src/linux-headers-$KERNEL)
decho HOSTHDRDIR=$HOSTHDRDIR
if [ -h $HOSTHDRDIR ]; then
    HOSTHDRDIR=$(realpath $HOSTHDRDIR)
    decho HOSTHDRDIR is a symlink pointing to $HOSTHDRDIR
    DESTHDRDIR=$TEMPDIR/initramfs/usr/src/$(basename $HOSTHDRDIR)
    decho DESTHDRDIR=$DESTHDRDIR
    $mkdir $(dirname $DESTHDRDIR) || cleanup 1
    $ln -s $(basename $HOSTHDRDIR) $TEMPDIR/initramfs/usr/src/linux-headers-$KERNEL || cleanup 1
else
    DESTHDRDIR=$TEMPDIR/initramfs/usr/src/linux-headers-$KERNEL
    decho DESTHDRDIR=$DESTHDRDIR
    $mkdir $(dirname $DESTHDRDIR) || cleanup 1
fi


decho '********** INSTALLING HEADERS **************************************************'
# Copy headers over, too
#
# NOTE: This is unneeded for boot, but needed if we want to use booting our
#       initrd as the installation method for modules and headers (e.g.,
#       modinject).
#
$cp -a $HOSTHDRDIR $DESTHDRDIR || cleanup 1


# Pick a compressor
decho '********** PICKING A COMPRESSOR ************************************************'
# FIXME: Tried to add lz4, but after initially thinking it worked, I can't get
#        5.4 to boot with an lz4 compressed initrd... removed it for now.
fast_list="zstd gzip xz"
best_list="xz zstd gzip"
comp_cmd=
config=$BASEDIR/boot/config-$KERNEL
if [ ! -f $config ]; then
    echo "WARNING: kernel config $config missing, default to gzip compression"
    comp_cmd="gzip"
else
    case $COMPMODE in
        fast)
            comp_list=$fast_list
            ;;
        best)
            comp_list=$best_list
            ;;
        *)
            echo "WARNING: invalid COMPMODE $COMPMODE, using fast"
            comp_list=$fast_list
    esac
    for comp in $comp_list; do
        # check for binary
        which $comp >/dev/null || continue
        # check kernel config
        grep -q CONFIG_RD_${comp^^}=y $config || continue
        comp_cmd="$comp"
        break
    done
fi
if [ -z "$comp_cmd" ]; then
    comp_cmd="cat"
elif [ "$opt_verbose" != 0 ]; then
    comp_cmd+=" -v"
fi
case ${comp_cmd%% *} in
    lz4)
        comp_cmd+=" -l"
        ;;
    xz)
        comp_cmd+=" --check=crc32"
        ;;
esac
echo "Chose compressor: $comp_cmd"


# Create the compressed image
decho '********** CREATING COMPRESSED CPIO IMAGE **************************************'
pushd >/dev/null $TEMPDIR/initramfs &&
find . | $cpio -o -H newc | $comp_cmd > ../initramfs.img &&
popd >/dev/null || cleanup 1

rm -f $INITRAMFS_TARGET
$mv $TEMPDIR/initramfs.img $INITRAMFS_TARGET

echo "Done; initramfs is $(du -h $INITRAMFS_TARGET | awk '{print $1}')."
echo
cleanup 0
