#!/bin/ash
#
# Copyright 2012-2025 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script unmounts /sysroot, all sqsh_layers, sqsh_layerdev, etc

. /ruckusrd-common.sh

# exit immediately if a command fails
set -e

# check to see of anything was using a zpool
zpools=
for zp in $(zpool list -H |awk '{print $1}'); do
    if (grep -q "^$zp" /proc/mounts); then
        zpools="$zpools $zp"
    fi
done

# unmount virtual filesystems
sysroot_umount_vfs

# unmount everything else
for x in /sysroot /sqsh_layer-* /sqsh_layerdev /tmproot; do
    if (grep -q $x /proc/mounts); then
        umount $x
    fi
done

# export any used zpools
for zp in $zpools; do
    zpool export $zp
done

# deactivate unnneeded lvm
deactivate_unneeded_lvm
